name: ar_ai_messaging_client_frontend
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  logger: ^1.1.0
  floating_bottom_navigation_bar: ^1.5.2
  google_fonts: ^3.0.1
  jiffy: ^5.0.0
  cached_network_image: ^3.2.1
  stream_chat_flutter_core: ^4.3.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.19.2
  firebase_storage: ^10.0.3
  cloud_firestore: ^3.1.18
  cloud_functions: ^3.3.2
  google_sign_in: ^5.4.0
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  image_picker: ^0.8.5+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
